### ISSUE TITLE
Errors showing twice in diagnostics list

### ISSUE THREAD

**Issue by jim-at-jibba** [josa42/coc-go#114]
Hey,

Each error is showing twice in the diagnostics list.

<img width="826" alt="Screenshot 2020-10-24 at 15 39 12" src="https://user-images.githubusercontent.com/7897877/97084452-15250400-160f-11eb-9933-9ccd217da0c0.png">

**Comment by vcavallo** [comment]
I was about to open a related issue. As far as I can tell, `coc-go` installs `gopls` on its own - which means that if you _already_ have `gopls` installed, you likely have two `gopls` servers running and may even have other processing accessing it (`vim-go`, `coc-go`, `coc` itself, other stuff - i'm still untangling all this myself).

I've been trying to debug why I'm constantly getting two `gopls serve` commands running in my process manager when opening my editor (and subsequently running into severe memory issues). The most helpful thing I did today was [_uninstall_](https://stackoverflow.com/questions/13792254/removing-packages-installed-with-go-get) `gopls`. Now when I do `which gopls` I get _nothing_. However, since I have `coc-go` installed, when I start neovim I _do_ get a `gopls serve` command running and all the features work as expected.

Uninstall `gopls` at your own risk - I don't know what else you have depending on it.

**Comment by jim-at-jibba** [comment]
@vcavallo can I ask a possibly unrelated question. But do the errors automatically update in your editor? I only see them when I open a file or restart COC. It basically makes it impossible to use Vim for go

**Comment by josa42** [comment]
I don't think this is related to `coc-go`.

My guess would be that you have both gopls [set up as a language server](https://github.com/neoclide/coc.nvim/wiki/Language-servers#go) and `coc-go` installed.
